Added kyverno and updated ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -4,11 +4,135 @@ on:
   push:
     branches:
       - main
+      - kyverno-chainsaw
+      
   pull_request:
     branches:
       - main
 
 jobs:
+  ci:
+    if: github.ref == 'refs/heads/main' || github.event.pull_request.draft == false
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [self-hosted-ubuntu, ubuntu-latest-8-cores, windows-latest]
+        arch: [amd64, arm64]
+        exclude:
+          - os: ubuntu-latest-8-cores
+            arch: arm64
+          # - os: ubuntu-latest-8-cores
+          #   arch: amd64
+          - os: windows-latest
+            arch: arm64
+          - os: windows-latest
+            arch: amd64
+          - os: self-hosted-ubuntu
+            arch: arm64    
+          - os: self-hosted-ubuntu
+            arch: amd64    
+
+    env:
+      KUBECONFIG: ${{ github.workspace }}/contexts/local/.kube/config
+      TALOSCONFIG: ${{ github.workspace }}/contexts/local/.talos/config
+      PRIVATE_DOMAIN_NAME: private.test
+      DNS_SERVER_IP: "10.5.255.200"
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Create .docker-cache directory
+        run: mkdir -p .docker-cache
+
+      - name: Cache .docker-cache
+        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
+        with:
+          path: .docker-cache
+          key: docker-cache-${{ runner.os }}-${{ github.sha }}
+          restore-keys: docker-cache-${{ runner.os }}-
+
+      - name: Install Aqua
+        uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
+        with:
+          aqua_version: v2.40.0
+
+      - name: Install tools using Aqua
+        run: aqua install
+                        
+      - name: Install Python and create a virtual environment
+        run: |
+          python -m venv .venv
+          echo "PATH=${{ github.workspace }}/.venv/bin:$PATH" >> $GITHUB_ENV
+          pip install -r requirements.txt
+
+      - name: Create arbitrary ansible secret file
+        run: |
+          mkdir -p $HOME/.ansible
+          echo "pwd123" >> $HOME/.ansible/secret
+
+      - name: Set up Go
+        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
+        with:
+          go-version: '1.22.8'
+    
+      - name: Authenticate with PAT
+        run: |
+          git config --global url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
+
+      - name: Set GOPRIVATE to prevent checking sum.golang.org
+        run: |
+          echo "GOPRIVATE=github.com/windsor-hotel/*" >> $GITHUB_ENV
+
+      - name: Install Windsor CLI
+        run: |
+          go install github.com/windsor-hotel/cli/cmd/windsor@main
+                  
+      - name: Set Windsor context to local
+        run: |
+          windsor init local 
+              
+      - name: Bootstrap the cluster
+        env:
+          TF_VAR_blueprints_deploy_key: ${{ secrets.BLUEPRINTS_DEPLOY_KEY }}
+        run: |
+          trap '[[ $? -ne 0 ]] && ./bin/k8s-diagnose' EXIT
+          windsor up
+          trap - EXIT
+
+      - name: Wait for Grafana to be ready
+        run: |
+          # Disable exit on error
+          set +e
+
+          trap '[[ $? -ne 0 ]] && ./bin/k8s-diagnose' EXIT
+
+          # Run curl check up to 10 times
+          for i in {1..10}; do
+            status_code=$(curl -k -o /dev/null -s -w "%{http_code}" https://grafana.${PRIVATE_DOMAIN_NAME}/login)
+
+            if [ "$status_code" -eq 200 ]; then
+              echo "Grafana is ready."
+              exit 0  # Exit the script successfully if the endpoint returns 200
+            else
+              echo "Attempt $i: Grafana not ready. HTTP status code: $status_code."
+            fi
+
+            if [ $i -eq 10 ]; then
+              echo "Grafana did not return 200 OK after 10 attempts."
+              exit 1  # Exit with failure after 10 unsuccessful attempts
+            fi
+            
+            sleep 5  # Wait 5 seconds before the next attempt
+          done
+
+          trap - EXIT
+
+      - name: Run Tests
+        run: |
+          trap '[[ $? -ne 0 ]] && ./bin/k8s-diagnose' EXIT
+          task test
+          trap - EXIT
+
   checkov:
     runs-on: ubuntu-latest
     steps:
