Updated ci-flow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+      - windsor-up-test
   pull_request:
     branches:
       - main
@@ -34,31 +35,196 @@ jobs:
         run: mkdir -p .docker-cache
 
       - name: Cache .docker-cache
-        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
+        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
         with:
           path: .docker-cache
           key: docker-cache-${{ runner.os }}-${{ github.sha }}
           restore-keys: docker-cache-${{ runner.os }}-
 
-      - name: Install Aqua
+      # Install Aqua
+      - name: Install Aqua on Linux/macOS
+        if: runner.os == 'Linux' || runner.os == 'macOS'
         uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
         with:
-          aqua_version: v2.44.1
+          aqua_version: v2.28.0
 
+      - name: Set aqua path
+        if: runner.os == 'Linux' || runner.os == 'macOS'
+        run: |
+          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
+    
+      # Install tools
       - name: Install tools
-        run: aqua install
-      
-      - name: Install Windsor CLI from Main Branch
         run: |
-          git clone https://github.com/windsorcli/cli.git
-          cd cli/cmd/windsor
-          go build -o windsor
-          chmod +x windsor
-          mkdir -p $HOME/.local/bin
-          mv windsor $HOME/.local/bin
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
+          aqua install     
 
-      - name: Print Windsor Version
+      # Install Windsor CLI
+      - name: Install Windsor CLI
+        uses: windsorcli/action/.github/actions/windsorcli@078842a08b468bd2278563bbc929e9d968095988 # v0.2.0
+        with:
+          version: ${{ env.WINDSOR_VERSION }}
+          install_folder: ${{ github.workspace }}/bin
+          context: local
+
+      # Windsor Up
+      - name: Windsor Up on Linux/macOS
+        if: runner.os == 'Linux' || runner.os == 'macOS'
         run: |
-          windsor version
-          
+          # Set WINDSOR_PROJECT_ROOT
+          export WINDSOR_PROJECT_ROOT="${{ github.workspace }}"
+
+          # Windsor Init
+          windsor init local
+
+          # Windsor Up
+          windsor context get
+          windsor up --install --verbose
+
+      - name: Windsor Up on Windows
+        if: runner.os == 'Windows'
+        run: |
+          # Set WINDSOR_PROJECT_ROOT
+          $env:WINDSOR_PROJECT_ROOT="${{ github.workspace }}"
+
+          # Windsor Init
+          windsor init local
+
+          # Windsor Up
+          windsor context get
+          windsor up --install --verbose
+
+        shell: powershell
+
+      # Windsor Down
+      - name: Windsor Down on Linux/macOS
+        if: always() && (runner.os == 'Linux' || runner.os == 'macOS')
+        run: |
+          # Set WINDSOR_PROJECT_ROOT
+          export WINDSOR_PROJECT_ROOT="${{ github.workspace }}"
+
+          # Windsor Down
+          windsor down --clean
+
+      - name: Windsor Down on Windows
+        if: always() && (runner.os == 'Windows')
+        run: |
+          # Set WINDSOR_PROJECT_ROOT
+          $env:WINDSOR_PROJECT_ROOT="${{ github.workspace }}"
+
+          # Windsor Down
+          windsor down --clean
+        shell: powershell
+
+      # Docker Clean
+      - name: Docker Clean on Linux/macOS
+        if: always() && (runner.os == 'Linux' || runner.os == 'macOS')
+        run: |
+          # Check for running containers and remove them
+          containers=$(docker ps -aq)
+          if [ -n "$containers" ]; then
+            echo "Removing containers..."
+            docker rm -f "$containers"
+          else
+            echo "No containers to remove."
+          fi
+
+          # Prune system, volumes, and networks
+          echo "Pruning Docker system, volumes, and networks..."
+          docker system prune -a -f
+          docker volume prune -f
+          docker network prune -f
+          docker system prune -a -f
+
+
+      - name: Docker Clean on Windows
+        if: always() && runner.os == 'Windows'
+        run: |
+          # Check for running containers and remove them
+          $containers = docker ps -aq
+          if ($containers) {
+            Write-Output "Removing containers..."
+            docker rm -f $containers
+          } else {
+            Write-Output "No containers to remove."
+          }
+
+          # Prune system, volumes, and networks
+          Write-Output "Pruning Docker system, volumes, and networks..."
+          docker system prune -a -f
+          docker volume prune -f
+          docker network prune -f
+          docker system prune -a -f
+
+        shell: powershell
+
+      # Windsor Clean
+      - name: Windsor Clean on Linux/macOS
+        if: always() && (runner.os == 'Linux' || runner.os == 'macOS') 
+        run: |
+          if [ "$GITHUB_WORKSPACE" == "/" ]; then
+            echo "Error: GITHUB_WORKSPACE is the root folder. Aborting cleanup."
+            exit 1
+          fi
+
+          if [ ! -d "$GITHUB_WORKSPACE" ]; then
+            echo "Error: GITHUB_WORKSPACE is not a directory. Aborting cleanup."
+            exit 1
+          fi
+          sudo rm -rf $GITHUB_WORKSPACE/.windsor
+          sudo rm -rf $GITHUB_WORKSPACE/*.*
+          sudo rm -rf $GITHUB_WORKSPACE/terraform
+          sudo rm -rf $GITHUB_WORKSPACE/kustomize
+          rm -rf ./.yamllint
+          rm -rf ./.gitignore
+          rm -rf ./.editorconfig
+
+      - name: Windsor Clean on Windows
+        if: always() && runner.os == 'Windows'
+        run: |
+          if ($env:GITHUB_WORKSPACE -eq "C:\") {
+            Write-Error "Error: GITHUB_WORKSPACE is the root folder. Aborting cleanup."
+            exit 1
+          }
+
+          if (-Not (Test-Path -Path $env:GITHUB_WORKSPACE -PathType Container)) {
+            Write-Error "Error: GITHUB_WORKSPACE is not a directory. Aborting cleanup."
+            exit 1
+          }
+
+          Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse | ForEach-Object {
+            try {
+              Remove-Item -Recurse -Force $_.FullName
+            } catch {
+              Write-Warning "Warning: Could not delete $_.FullName because it is in use."
+            }
+          }
+        shell: powershell
+
+      # Remove Tools
+      - name: Remove tools
+        if: always() && (runner.os == 'Linux' || runner.os == 'macOS') 
+        run: |
+          aqua rm --all 2>&1
+      
+      # Check if any files still exist in the workspace and report them if found (Linux/macOS)
+      - name: Check for remaining files on Linux/macOS
+        if: always() && (runner.os == 'Linux' || runner.os == 'macOS')
+        run: |
+          remainingFiles=$(find . -maxdepth 1 -type f)
+          if [ -n "$remainingFiles" ]; then
+            echo "Error: Found files in the workspace that should be removed:"
+            echo "$remainingFiles"
+            exit 1
+          fi
+
+      # Check if any files still exist in the workspace and report them if found (Windows)
+      - name: Check for remaining files on Windows
+        if: always() && runner.os == 'Windows'
+        run: |
+          $remainingFiles = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse
+          if ($remainingFiles) {
+            Write-Output "Error: Found files in the workspace that should be removed:"
+            $remainingFiles | ForEach-Object { Write-Output $_.FullName }
+            exit 1
+          }
+        shell: powershell
